apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-protocols

spec:
  schedule: "0 7 * * *"
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1

  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: update-protocols
              image: yroochun/update-protocols:latest
              imagePullPolicy: Always
              command:
                - python
                - create_protocols.py

              env:
                - name: ES_USER
                  valueFrom:
                    secretKeyRef:
                      name: gcp-es-credentials
                      key: es_user

                - name: ES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: gcp-es-credentials
                      key: es_password

              ports:
                - containerPort: 8000

          imagePullSecrets:
            - name: regcred

          restartPolicy: OnFailure